#!/bin/sh
echo "(Grabbing ssh)"
mkdir $HOME/bin

SSHV="SSH_CLIENT SSH_TTY SSH_AUTH_SOCK SSH_CONNECTION DISPLAY"

for x in ${SSHV} ; do
    (eval echo $x=\$$x) | sed  's/=/="/
                                s/$/"/
                                s/^/export /'
done 1>$HOME/bin/fixssh
chmod 0700 $HOME/bin/fixssh

echo "(Reattaching to screen)"
screen -d -RR

